name: drive_wise
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sensors_plus: ^6.1.0
  geolocator: ^13.0.1
  http: ^1.1.0
  permission_handler: ^11.1.1   # For permissions handling in Android
  scidart: ^0.0.1 
  savgol: ^0.1.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
